# carbon_import_harfbuzz_raster(<name> <harfbuzz-target> [GLOBAL])
#
# Defines the imported target <name> for HarfBuzz's raster library (HarfBuzz 13 and later) when a HarfBuzz package
# installed the library without a CMake target of its own, as Meson-built packages do (vcpkg's, those of Linux
# distributions). The library is looked for in the folder of HarfBuzz's own library, for each configuration that
# <harfbuzz-target> has, and its header next to HarfBuzz's headers. Nothing is defined when it is not there. Used by
# Carbon's build and again by CarbonConfig.cmake, so that an installed Carbon links the same library.
function(carbon_import_harfbuzz_raster NAME HARFBUZZ)
    if(TARGET ${NAME} OR NOT TARGET ${HARFBUZZ})
        return()
    endif()
    get_target_property(aliased ${HARFBUZZ} ALIASED_TARGET)
    if(aliased)
        set(HARFBUZZ ${aliased})
    endif()

    set(include_found OFF)
    get_target_property(include_dirs ${HARFBUZZ} INTERFACE_INCLUDE_DIRECTORIES)
    foreach(include_dir IN LISTS include_dirs)
        if(EXISTS "${include_dir}/hb-raster.h" OR EXISTS "${include_dir}/harfbuzz/hb-raster.h")
            set(include_found ON)
        endif()
    endforeach()
    if(NOT include_found)
        return()
    endif()

    # IMPORTED_LOCATION_<CONFIG> for each configuration, then IMPORTED_LOCATION ("-" stands for no suffix).
    get_target_property(configurations ${HARFBUZZ} IMPORTED_CONFIGURATIONS)
    set(suffixes "")
    foreach(configuration IN LISTS configurations)
        string(TOUPPER "_${configuration}" suffix)
        list(APPEND suffixes "${suffix}")
    endforeach()
    list(APPEND suffixes "-")
    set(locations "")
    foreach(suffix IN LISTS suffixes)
        if(suffix STREQUAL "-")
            set(suffix "")
        endif()
        get_target_property(harfbuzz_library ${HARFBUZZ} IMPORTED_LOCATION${suffix})
        get_target_property(harfbuzz_import_library ${HARFBUZZ} IMPORTED_IMPLIB${suffix})
        if(harfbuzz_import_library)
            set(harfbuzz_library "${harfbuzz_import_library}")
        endif()
        if(NOT harfbuzz_library)
            continue()
        endif()
        get_filename_component(library_dir "${harfbuzz_library}" DIRECTORY)
        get_filename_component(library_name "${harfbuzz_library}" NAME)
        string(REPLACE "harfbuzz" "harfbuzz-raster" raster_name "${library_name}")
        if(EXISTS "${library_dir}/${raster_name}")
            list(APPEND locations "${suffix}|${library_dir}/${raster_name}")
        endif()
    endforeach()
    if(NOT locations)
        return()
    endif()

    if(ARGV2 STREQUAL "GLOBAL")
        add_library(${NAME} UNKNOWN IMPORTED GLOBAL)
    else()
        add_library(${NAME} UNKNOWN IMPORTED)
    endif()
    foreach(location IN LISTS locations)
        string(FIND "${location}" "|" separator)
        string(SUBSTRING "${location}" 0 ${separator} suffix)
        math(EXPR separator "${separator} + 1")
        string(SUBSTRING "${location}" ${separator} -1 path)
        set_target_properties(${NAME} PROPERTIES IMPORTED_LOCATION${suffix} "${path}")
        if(NOT suffix STREQUAL "")
            string(SUBSTRING "${suffix}" 1 -1 configuration)
            set_property(TARGET ${NAME} APPEND PROPERTY IMPORTED_CONFIGURATIONS ${configuration})
        endif()
    endforeach()
    target_link_libraries(${NAME} INTERFACE ${HARFBUZZ})
endfunction()
